on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'          
          classpath: './'
          changeLogFile: 'changeLog.xml'
          username: 'manish'
          password: 'InfoInfo@2022'
          url: 'jdbc:sqlserver://parteyserver.database.windows.net:1433;database=parteyDB;user=manish@parteyserver;password=InfoInfo@2022;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;'